version: '3.8'

services:
  phoenixtrade-backend:
    build: .
    container_name: phoenixtrade-backend
    ports:
      - "5001:5001"
    volumes:
      - ./user:/app/user
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - OCTOBOT_NO_TELEGRAM=1 
    restart: unless-stopped

  phoenixtrade-ui:
    build: ./phoenixtrade-ui
    container_name: phoenixtrade-ui
    ports:
      - "80:80"
    depends_on:
      - phoenixtrade-backend
    restart: unless-stopped
